### ISSUE TITLE
Are there any known issues using rotate: true?

### ISSUE THREAD

**Issue by nicolaswww** [Raruto/leaflet-rotate#1]
First of all thanks for maintaining the rotate branch :)

I'm implementing it in a free project that's map based and so far, at least visually, I haven't encountered any problems. Is there a list of known issues (and how to trigger them) using a Leaflet instance with `rotate: true`?

I will try to collaborate with this project if the implementation is effective in my project.

Regards!

**Comment by nicolaswww** [comment]
Ok I found an issue when the map has "maxBounds", when rotating it and play with the zoom after a while it starts to fail (when doing touch rotation it rotates too much and abruptly).

**Comment by Raruto** [comment]
Hi Nicolàs,

> Is there a list of known issues (and how to trigger them) using a Leaflet instance with rotate: true?

at current stage (**v 0.1.2**), they should be the same as listed here: https://github.com/fnicollet/Leaflet/issues

> I will try to collaborate with this project if the implementation is effective in my project.

Any additional help is welcome, not least because I'm not a core developer, and currently I don't have more time than them to devote to this feature: https://github.com/Leaflet/Leaflet/issues/268#issuecomment-421838981

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
> Ok I found an issue when the map has "maxBounds", when rotating it and play with the zoom after a while it starts to fail (when doing touch rotation it rotates too much and abruptly).

Hi @nicolaswww this appears to be a long-standing issue related to some functions within the `L.Map` class (eg. [`panInside`](https://leafletjs.com/reference#map-paninsidebounds), [`panInsideBounds`](https://leafletjs.com/reference#map-paninsidebounds), etc.). Are you able to tell me if has it improved in somehow with **v0.2.0**?

Ref: https://github.com/Raruto/leaflet-rotate/issues/18, https://github.com/Raruto/leaflet-rotate/pull/21 and [fnicollet/Leaflet/issues](https://github.com/fnicollet/Leaflet/issues)

**Comment by Raruto** [comment]
For completeness I report here what is described within https://github.com/Raruto/leaflet-rotate/pull/22#pullrequestreview-1283399252, because I think this is one of the main cause of some strange glitched animations that people have historically encountered with the [rotate](https://github.com/fnicollet/Leaflet/issues) branch.


> @heyajohnny Did you mean to apply the above patch? Ref: https://github.com/Raruto/leaflet-rotate/pull/22/commits/2de9c8aabf79aeb23ceef380506ad0b870f8fb5f and https://github.com/Raruto/leaflet-rotate/pull/22#pullrequestreview-1283232182
> 
> ---
> 
> Unfortunately the problem reported below is not solved with that patch.
> 
> https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/layer/vector/Renderer.js#L21-L55
> 
> To check this more clearly you can set [`zoomAnimation: false`](https://leafletjs.com/reference#map-zoomanimation) and moving between zoom levels 0 and 2.
> 
> During the zoom animation `L.Renderer::_updateTransform(zoom, center)` breaks the calculation of the origin of the panes (it is less noticeable with `zoomAnimation: true` because at the end of the zoom animation `L.Renderer::_update()` is called last which repositions correctly all coordinates by scaling them to the current zoom level, i.e. going from css transform `scale(0.5)` to `scale(1)`)
> 
> if you're interested in finding a solution I can publish a branch that where I'm doing some visual debugging on (although it's a bit messed up 😄).
> 
> Currently the problem occurs especially between zoom levels 0 and 2, due to the use of the following function to calculate the offset between the current origin (eg. at `zoomStart = 1`) and the next one (eg. at `zoomEnd = 0`).
> 
> ```js
> offset = this._map._latLngToNewLayerPoint(this._topLeft, zoom, center);
> ```
> 
> Basically, a wrong approximation of the origin is made because in that point the screen coordinates (pixel) are projected / converted into geographical coordinates (latlng) and vice-versa. And at that moment the origin is "shifted" from the real position (because there is no lat/lng associated for the current origin location which is outside the map bounds).
> 
> ---
> 
> Perhaps an optimal solution would be to follow the calculation done by the core (which instead starts on the center of the container to deduce the offset of the origin pixel), but for the moment this doesn't work because it would be necessary to update these calculations to pass into the "rotated" reference system (applying [some](https://github.com/Raruto/leaflet-rotate/blob/8e9f36858e8172931972b3adf68b23dfc74527fd/src/map/Map.js#L63-L96) appropriate rotation functions to the various pixel coordinates)
> 
> ```js
> // Leaflet/Leaflet/src/layer/vector/Renderer.js#L84-L93
> 
> _updateTransform(center, zoom) {
>   const scale = this._map.getZoomScale(zoom, this._zoom),
>     viewHalf = this._map.getSize().multiplyBy(0.5 + this.options.padding),
>     currentCenterPoint = this._map.project(this._center, zoom),
> 
>     topLeftOffset = viewHalf.multiplyBy(-scale).add(currentCenterPoint)
> 				  .subtract(this._map._getNewPixelOrigin(center, zoom));
> 
>     DomUtil.setTransform(this._container, topLeftOffset, scale);
> },
> ```
> 
> Ref: [Leaflet/Leaflet/src/layer/vector/Renderer.js#L84-L93](https://github.com/Leaflet/Leaflet/blob/d1016279f37652a78b53c35e826b3180e4f7f03f/src/layer/vector/Renderer.js#L84-L93)
>

**Comment by iamroh192** [comment]
q

**Comment by nicolaswww** [comment]
Hi @Raruto! I didn't see this before, thanks for the mention. I'll update that project right now and let you know if I find new problems. thank you so much!
