### ISSUE TITLE
Anyone got this working with Nuxt Leaflet?

### ISSUE THREAD

**Issue by digitalforgeangelo** [Raruto/leaflet-rotate#10]
As the title says... does anyone have this working?

**Comment by Raruto** [comment]
Hi digitalforangelo,

I don't think anyone here can help you, if you need help try asking on the dedicated forums or try to get in touch directly with the developer of that library:

- https://github.com/schlunsen/nuxt-leaflet/issues
- https://stackoverflow.com/search?q=nuxt-leaflet

_Have a nice day,
Raruto_
