### ISSUE TITLE
Show the default rotate button dynamically

### ISSUE THREAD

**Issue by RoboVij** [Raruto/leaflet-rotate#11]
The default rotate button is showing up automatically, right after importing the plugin. Is it possible to customize? So that we can decide whether to have the button or not based on a prop.

**Comment by Raruto** [comment]
I think so, since it is just a leaflet control (at most like the `L.Control.Zoom` you can just instantiate your own):

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/control/Rotate.js#L154-L168

_Have a nice day,
Raruto_
