### ISSUE TITLE
Blured text on a popup

### ISSUE THREAD

**Issue by oarque** [Raruto/leaflet-rotate#12]
Hi,
when I show a popup or a rotated map, the text on this popup is blured. 
If the map is not rotate the text is ok.
If unmark"transform" style on the "leaflet-popup  leaflet-zoom-animated".class, the text displays ok too.

Thanks for this job!

**Comment by Raruto** [comment]
Hi oarque,
could you please produce an example showing this bug?

_Have a nice day,
Raruto_

**Comment by oarque** [comment]
Sorry I had an error in my css project ;-(

Thanks anyway
