### ISSUE TITLE
Use Alt+Shift+Drag to rotate the map

### ISSUE THREAD

**Issue by 1Map** [Raruto/leaflet-rotate#14]
How can we achieve the same behaviour as in Openlayers (Use Alt+Shift+Drag to rotate the map) ?

**Comment by Raruto** [comment]
Hi @1Map,

you can write your own [handler](https://leafletjs.com/examples/extending/extending-3-controls.html) based on the default one (Shift + Key + Rotate):

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/map/handler/ShiftKeyRotate.js#L1-L52

_Have a nice day,
Raruto_
