### ISSUE TITLE
Compatibility with Leaflet 1.9.2

### ISSUE THREAD

**Issue by alessandro-dallatorre** [Raruto/leaflet-rotate#15]
I know that it states compatible with Leaflet 1.7
However, I tested this plugin with Leaflet 1.9.2 and everything works except from popups that stay anchored to the old position without getting the rotation transformation applied.
Could you please look into this?

**Comment by jasseur2017** [comment]
I ran into the same problem when working with draggable markers.

**Comment by Raruto** [comment]
Hi @alessandro-dallatorre,

every file included in this library does nothing but slightly alter (overriding) the prototypes of some functions defined in the core, eg:

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/layer/Popup.js#L4-L6

in particular, only two functions are modified within that file:

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/layer/Popup.js#L1-L65

as i am not a core developer either, please try to check yourself too if anything has changed in the meantime inside that file:

- [_animateZoom](https://github.com/Leaflet/Leaflet/blame/6b90c169d6cd11437bfbcc8ba261255e009afee3/src/layer/Popup.js#L250-L254)
- [_adjustPan](https://github.com/Leaflet/Leaflet/blame/6b90c169d6cd11437bfbcc8ba261255e009afee3/src/layer/Popup.js#L256-L310)

At the moment, you may be waiting a very long time before I get in on it...

_Thanks for any cooperation,
Raruto_

**Comment by Raruto** [comment]
@alessandro-dallatorre I did a quick test with version **leaflet@v1.9.2** and it seems ok to me.

If not, please also provide a public example that reproduces the issue, otherwise I consider this issue resolved

_Have a nice day,
Raruto_

**Comment by alessandro-dallatorre** [comment]
Yes, please wait and I'll post some code and screenshots.

**Comment by Raruto** [comment]
> popups that stay anchored to the old position without getting the rotation transformation applied.

@alessandro-dallatorre it is not clear what exactly you are referring to, but this should be the default behavior (markers, popups and tooltips by default are not added to `rotatePane`, see also: [Map Panes](https://leafletjs.com/reference#map-pane) documentationt and https://github.com/Raruto/leaflet-rotate/issues/2#issuecomment-889768730)

https://github.com/Raruto/leaflet-rotate/blob/2526fa91ef23c6d3c04c779feaddf0411ace69a8/src/map/Map.js#L230-L232

> please wait and I'll post some code and screenshots.

It's been a while, if you think there is still a problem please open a new specific issue and provide more detailed information about it

_I do my best to at least keep the plugin aligned with the main leaflet structure, but I don't have the resources to test or support only myself all the available features.._
