### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nakrout** [Raruto/leaflet-rotate#17]
Is it possible to provide leaflet-rotate.d.ts?
I am working on it. But, it needs more effort since I have to understand  first the source code of the plugin to implement it correctly.

Thanks for your help!

**Comment by Raruto** [comment]
Hi @nakrout,

>Is it possible to provide leaflet-rotate.d.ts?

I don't think I ever will, but any help is welcome.

> I am working on it. But, it needs more effort since I have to understand first the source code of the plugin to implement it correctly.

This project makes an extensive use of a technique also known as [Monkey Patching](https://en.wikipedia.org/wiki/Monkey_patch), in this regard, you can also find some information in the official leaflet documentation: [Extending Leaflet - Class Theory](https://leafletjs.com/examples/extending/extending-1-classes.html)

Once you understand that, just navigate the folder structure of both projects to know which classes/methods/properties are being changed or added:

- https://github.com/Leaflet/Leaflet/tree/main/src
- https://github.com/Raruto/leaflet-rotate/tree/master/src

as you can see the files in here should be pretty much the same.

_Have a nice day,
Raruto_

**Comment by nakrout** [comment]
Hello @Raruto,

Thanks for your support and the useful links. 
I find an existing [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) package [@types/leaflet-rotate](https://www.npmjs.com/package/@types/leaflet-rotate). It worked with no issue, at least for now.

Regards.
