### ISSUE TITLE
Does not rotate panes other than default

### ISSUE THREAD

**Issue by mike16889** [Raruto/leaflet-rotate#2]
I havea setup where I have my markers etc. spread out over panes as layers, that way certain types of items are always on top and others are always on the bottom.

This seems to brake the rotate plugin, watching the dom in devtools i can see the transforms changing on rotation for the default pane (the one the "leaflet-rotate-pane" class added) not the other panes.

Is there any way to force this plugin to also rotate these other panes? as they should be rotated as well.

**Comment by Raruto** [comment]
Hi mike,
without a concrete example it's hard to say...

If it can help you, here you find an example implementation done in combination with this library:

- https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/control.js#L584
- https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/control.js#L315
- https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/control.js#L918
- https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/marker.js#L66

anyway, you might try this first:

```js
let pane = map.getPane('customPane');

if (!pane) {
  
  // SEE: https://leafletjs.com/reference-1.7.1.html#map-createpane
  pane = map.createPane('customPane', map.getPane('rotatePane') || map.getPane('mapPane')); 
  
  // OPTIONAL: this pane is above markers but below popups.
  pane.style.zIndex = 625; 
}
```

_Have a nice day,
Raruto_

**Comment by mike16889** [comment]
Looks like that could work. Will try later tonight.

**Comment by mike16889** [comment]
That works, as long as markers are still only one the default pane. if I move them to another pane (even if it is a child of the default) the markers "drift" when zooming. poly layers are fine on other panes. I may be able to make it work by using the default pane for my markers and changing the z-index to be what my 'markers' pane is currently at.

**Comment by Raruto** [comment]
Hi mike,
custom "markerPanes" must be added to the "norotatePane" (this because only marker icons will be rotated, see [rotateWithView](https://github.com/Raruto/leaflet-rotate/blob/84338b2872d9f40c4c29740a8a9356b9b6c5869a/src/layer/marker/Marker.js#L71) option for more info):

```js
let pane = map.getPane('customPane');

if (!pane) {
  
  // SEE: https://leafletjs.com/reference-1.7.1.html#map-createpane
  // WRONG: pane = map.createPane('customPane', map.getPane('rotatePane') || map.getPane('mapPane')); 
  pane = map.createPane('customPane', map.getPane('norotatePane') || map.getPane('mapPane')); 
  
  // OPTIONAL: this pane is above markers but below popups.
  pane.style.zIndex = 625; 
}

L.marker([51.51, -0.12], {pane: 'customPane'}).addTo(map);
```

**Reference:**

- [src/layer/marker/Marker.js](https://github.com/Raruto/leaflet-rotate/blob/84338b2872d9f40c4c29740a8a9356b9b6c5869a/src/layer/marker/Marker.js)
- [src/map/Map.js](https://github.com/Raruto/leaflet-rotate/blob/84338b2872d9f40c4c29740a8a9356b9b6c5869a/src/map/Map.js)

_Have a nice day,
Raruto_

**Comment by mike16889** [comment]
Thanks, that solves it completely. as well as an issue that I know i was going to face eventually, where some markers should always stay 'upright' (default behaviour) but some are intentionally rotated to go with the map so should go with the tiles.
