### ISSUE TITLE
toggling leaflet.control.rotate breaks rotate functionality on map

### ISSUE THREAD

**Issue by rphlo** [Raruto/leaflet-rotate#23]
When adding the leaflet.control.rotate Control it add a listener on rotate map event

```js
onAdd: function () {
  ...
  map.on('rotate', ...)
},
```

However when the control is removed the event listener is not removed from the map, and when calling map.setBearing or triggering the rotate event it triggers a JS error as the control does not exist anymore.
Removing the event listener in onRemove function would solve this issue.

**Comment by Raruto** [comment]
@rphlo It looks like you're right, feel free to submit a pull request to fix it.

👋 Raruto

**Comment by Raruto** [comment]
If so, can you attach some jsfiddle (or similar) with the tests you've already done?

Just to speed up debugging a little bit ☺️.
