### ISSUE TITLE
How can I sponsor this project?

### ISSUE THREAD

**Issue by siimaoo** [Raruto/leaflet-rotate#29]
Is there a way to sponsor this project? It's very helpful and a must have feature in maps that I created.

**Comment by Raruto** [comment]
Hi @siimaoo,
first of all thanks for the thought.

I'm not an expert on the subject, but if I remember correctly many sponsorship platforms charge substantial commissions to individual developers (that is, individuals, not companies), and in many cases additional you must also consider taxation fees as these for international transactions...

BTW, at the moment, given the size of project (rather than few pennies), I'd be really happy if some other developers would join to keep the project alive.

If you think this plugin is a "must-have" for your daily work, you can start, for example, how to write some tests that we could add here.

_An single developer has limited knowledge and capabilites_
👋 Raruto

**Comment by siimaoo** [comment]
can I make a PR with docs improvements? how to setup, how to use with react, common issues etc etc?

**Comment by Raruto** [comment]
@siimaoo for sure, whatever you think might be useful 👌

As for react, do you mean how to use it with a JS bundler?

**Comment by siimaoo** [comment]
I mean how to integrate this lib with react-leaflet and maybe I'll create an exemple repo

**Comment by ragavendra** [comment]
I found that my app stopsnearme.ca wasn't rotating and I found this library. I just set it up a while ago and really appreciate all the efforts put into it.

I saw that the app was rotating a bit more faster and wasn't sure which setting to update for it if there is any. Then, I was looking for documentation and found this post. Yes, I would be interested in the documentation.

> If you think this plugin is a "must-have" for your daily work, you can start, for example, how to write some tests that we could add here.
> 

I am between jobs now and can help with supporting this project like writing some tests as well as this can help with my next gig. I would appreciate if there is some guidance on this part.

PS - I didn't mean to add comment to a closed issue but rather offer my aid in contributing if possible.

**Comment by Raruto** [comment]
Hi @ragavendra,

> writing some tests as well as this can help with my next gig. I would appreciate if there is some guidance on this part.

[lukeed/uvu](https://github.com/lukeed/uvu) is used for performing semi-automated tests.

I talked about it a little in here (they are different repos but the code structure/testing logic is the same):
- https://github.com/Raruto/leaflet-rotate/pull/34
- https://github.com/Raruto/leaflet-elevation/issues/233
- https://github.com/Raruto/leaflet-elevation/issues/259

Additionally:
- [/test/index.html](https://github.com/Raruto/leaflet-rotate/blob/3dc29513cc223c22d0c66600c8289a92a0cb71af/test/index.html) it's usually a file I use to test changes in development (`npm run dev`)
- [/lib/debug.js](https://github.com/Raruto/leaflet-rotate/blob/3dc29513cc223c22d0c66600c8289a92a0cb71af/lib/debug.js) is a support library that could be useful for showing some debug info about your app at runtime (`L.Rotate.debug(map);`)
- [/examples](https://github.com/Raruto/leaflet-rotate/tree/3dc29513cc223c22d0c66600c8289a92a0cb71af/examples) folder contains all the tested files ("automatic" or "manual"), see also [`leaflet-elevation/examples`](https://github.com/Raruto/leaflet-elevation/tree/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/examples) (that means, if necessary, you can also use multiple `.spec.js` files
)
- [`console.assert`](https://developer.mozilla.org/en-US/docs/Web/API/console/assert_static) I don't use it yet, but it might come in handy in debugging runtime code

👋 Raruto

**Comment by ragavendra** [comment]
Thanks @Raruto for all this information. I will try and work on it whenever I get a chance. I will also try to see if I can improve the docs or relevant areas as well.
