### ISSUE TITLE
all markers set to draggable

### ISSUE THREAD

**Issue by mike16889** [Raruto/leaflet-rotate#3]
when including this plugin, all markers are set to draggable by default. this breaks compatibility with plugins like marker cluster.

issue can be seen on the demo. comment out the inclusion of this plugin and the issue goes away.

I have had a quick look at the code and cannot see where the default is changed from the norm of being disabled.

**Comment by Raruto** [comment]
Hi mike16889,

maybe there is a wrong condition here (ie. `this.dragging`):

https://github.com/Raruto/leaflet-rotate/blob/84338b2872d9f40c4c29740a8a9356b9b6c5869a/src/layer/marker/Marker.js#L88

[here](https://github.com/Leaflet/Leaflet/blob/ce266a8c77731f83e8e9e674cf20712012f9ab19/src/layer/marker/Marker.js#L280-L301) you can check out that same function in the core library.

_Raruto_

**Comment by Raruto** [comment]
Patched in version **0.1.3**

**Comment by mike16889** [comment]
@Raruto can confirm this fixes it. thank you.
