### ISSUE TITLE
ScrollWheelZoom

### ISSUE THREAD

**Issue by SensSebastianSchlosser** [Raruto/leaflet-rotate#33]
Hi!

I am using your extention for quite a while in my application. I saw in your code, that you have implemented some handlers from Leaflet (like TouchZoom, etc.)
There is a further handler called "ScrollWheelZoom":
https://github.com/Leaflet/Leaflet/blob/v1.9.3/src/map/handler/Map.ScrollWheelZoom.js

Is there a chance, that you will implement that into your repo?
Should I assist you with creating a fork a create a pull request (I certainly gurateed you, that is not a good idea :D )?

**Comment by SensSebastianSchlosser** [comment]
Closed because resolved by a setting I missed 😢

**Comment by xTorped0** [comment]
> Closed because resolved by a setting I missed 😢

could u help me?I faced the same problem but can`t find an exist setting for it
