### ISSUE TITLE
Question: Is there an option to rotate the marker from center?

### ISSUE THREAD

**Issue by DSoftwareArtist** [Raruto/leaflet-rotate#40]
@Raruto , 
### Currently, the behavior of the marker rotation is like this:

<img src="https://github.com/Raruto/leaflet-rotate/assets/13848044/ff8156df-470e-49e1-b671-0f24f03af466" width="200"/>

### But what I want to achieve is like this:
<img src="https://github.com/Raruto/leaflet-rotate/assets/13848044/3f98d3e2-efc0-436f-b72b-2ec8b9dc1963" width="200"/>

Here's my code:

```js
const marker = L.marker( L.latLng(0,0), {
   draggable: false,
   icon: L.icon( ... )
}).addTo(map)

marker.setRotation(70) 
```

I hope there's an option that I can apply for this. Thanks!

**Comment by DSoftwareArtist** [comment]
I also don't think if the angle is properly set. @Raruto 
``` 
const x = L.marker(L.latLng(0,0)).bindTooltip('<b>' + 'reamon' + '</b>').addTo(map)
x.setRotation(30)
```
![Screenshot from 2023-08-31 16-21-29](https://github.com/Raruto/leaflet-rotate/assets/13848044/fa9f9963-6f25-4140-9b57-2e7b6f7d7b60)

**Comment by Raruto** [comment]
Hi Reamon

> Is there an option to rotate the marker from center?

I don't think so (out of the box).

Eventually you could test with some other `L.Icon` properties, eg:

- https://leafletjs.com/reference#icon-iconanchor

BTW, please start poring over the code to get a feel for possibile alternatives.

For instance, you from here:

https://github.com/Raruto/leaflet-rotate/blob/48e97a6408df7796b3e06e6d8eb0729eb504b1be/src/layer/marker/Marker.js#L1-L159

https://github.com/Raruto/leaflet-rotate/blob/48e97a6408df7796b3e06e6d8eb0729eb504b1be/src/layer/marker/Icon.js#L1-L38

With effort, you should be able to come up with something similar on your own.

👋 Raruto
