### ISSUE TITLE
How do I disable `scrollWheelZoom` handler?

### ISSUE THREAD

**Issue by kemy971** [Raruto/leaflet-rotate#41]
Hello, I use leaflet to annotate images. Your plugin is very useful for my project, because it allows me to rotate images, it's great. My problem is that since I've been using your plugin, I can't disable the scrollWheelZoom on the image. Is there a solution?

**Comment by Raruto** [comment]
Hi Kèmy,

it should be enough:

```js
shiftKeyRotate: false,
```

To be sure, also take a look at the others handlers within the [src/map/handler](https://github.com/Raruto/leaflet-rotate/blob/48e97a6408df7796b3e06e6d8eb0729eb504b1be/src/map/handler/) folder:

## • src/map/handler/ShiftKeyRotate.js

https://github.com/Raruto/leaflet-rotate/blob/48e97a6408df7796b3e06e6d8eb0729eb504b1be/src/map/handler/ShiftKeyRotate.js#L1-L56

👋 Raruto

**Comment by kemy971** [comment]
It works well ! Merci
