### ISSUE TITLE
Allow iPhone Compass requestPermission()

### ISSUE THREAD

**Issue by ttooo** [Raruto/leaflet-rotate#44]
This isn't an issue, I found a fix, so if you want to add it for iPhone support it's good. By default on iPhone devices the compass access is not authorized, you can show this code to ensure the iPhone support will work after permission asked : 

![allow-iphone](https://github.com/Raruto/leaflet-rotate/assets/19242180/637244d1-965e-486b-8547-25b194588d9f)

```js
// Compass mode
      else if (!map.compassBearing.enabled()) {
        map.touchRotate.disable();
        // map.compassBearing.enable(); // -- before

        // new code added ---> start
        if (DeviceOrientationEvent && typeof DeviceOrientationEvent.requestPermission === "function") {
          DeviceOrientationEvent.requestPermission().then(function (permissionState) {
            if (permissionState === "granted") {
              map.compassBearing.enable();
            }
          });
        } else {
          map.compassBearing.enable();
        }
        // new code added <--- end
      }
```

**Comment by Raruto** [comment]
Thanks @ttooo, I can't test but please send a PR anyway.

👋 Raruto
