### ISSUE TITLE
Bearing with setActiveArea plugin incompatible

### ISSUE THREAD

**Issue by ttooo** [Raruto/leaflet-rotate#45]
I use this [plugin](https://github.com/Mappy/Leaflet-active-area) to set a specific area in my app.

The goal is to be able to display a full viewport map. And to set a **specific area so the zoom, setview and all actions happens in this specific area**. Also, this specific area allows me to change its height and width (for example if I change my slider height to display more data). So it's really usefull.

The bearing is also very usefull for me especially to launch an itinerary, so user understands with compass where he is. When bearing is set to 0 I have no issue, but **as soon as I change the bearing the center of my sepecific area is no more respected and it does weird things**.

Any idea about how to fix the center to be the active area one ?

Thanks in a lot

<img width="321" alt="active-area" src="https://github.com/Raruto/leaflet-rotate/assets/19242180/d97503b1-a145-4db8-9820-6885ca705aa2">

**Comment by Raruto** [comment]
That plugin also makes extensive use of [`L.Map.include`](https://github.com/Mappy/Leaflet-active-area/blob/f4300e288735c3290b26930a16a2463070a1beab/src/leaflet.activearea.js#L15) (to change the default behavior of some core functions).

It's a difficult solution, but the only way is to overriding them yourself within your code (as done by both plugins) to make them handle the rotated bounds (or fork that repo...).

👋 Raruto
