### ISSUE TITLE
Not working leaflet-rotatedmarker

### ISSUE THREAD

**Issue by clopezpro** [Raruto/leaflet-rotate#47]
if use 

```js
import 'leaflet-rotate'
import 'leaflet-rotatedmarker'

L.marker(latlng, {
      icon: iconRealTime,
      rotationAngle: feature.properties?.orientation ?? 0,
    }
```

rotationAngle not work

**Comment by clopezpro** [comment]
use 

```
L.marker(latlng, {
      icon: iconRealTime,
      rotation: feature.properties?.orientation ?? 0,
    },
    )
```
and this not use rotateZ(35deg), use rotate(35rad) in css
import 'leaflet-rotatedmarker'
![image](https://github.com/Raruto/leaflet-rotate/assets/27446663/b56ebb41-362e-4512-b27b-3a532484ab16)
 
import 'leaflet-rotate'
![image](https://github.com/Raruto/leaflet-rotate/assets/27446663/e56c8519-99bf-4b83-add7-d814985b129d)

**Comment by Raruto** [comment]
It's developers job knowing how to integrate other code/libraries..

As an inspiration, you can see this fork: https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/libs/leaflet-distance-marker.js

👋 Raruto
