### ISSUE TITLE
Rotating Svg overlays

### ISSUE THREAD

**Issue by cubecleveland** [Raruto/leaflet-rotate#5]
IS there any way to extned this to roatte svg ovelrays ?

**Comment by Raruto** [comment]
Hi cubecleveland,

if you are referring to [SVGOverlay](https://leafletjs.com/reference#svgoverlay), I think I've never used them before...

However, as you can see, this library has the same code structure as the core library:

- https://github.com/Raruto/leaflet-rotate/tree/master/src/layer
- https://github.com/Leaflet/Leaflet/tree/master/src/layer

it could also be that it works without changes (by any chance **have you tried before asking?**), otherwise you can start from the native code to try to understand the necessary changes: [https://github.com/Leaflet/Leaflet/tree/master/src/layer/SVGOverlay.js](https://github.com/Leaflet/Leaflet/blob/fb0b2a169ebde77a8bed1715bb07d436b60328a2/src/layer/SVGOverlay.js)

as you can see [here](https://github.com/Raruto/leaflet-rotate/blob/master/src/layer/vector/SVG.js) extending the default leaflet behavior is nothing too much complicated.

_Have a nice day,
Raruto_

**Comment by cubecleveland** [comment]
Thanks for your answer.

Is there docs regarding the api list...
Trying to bascially just put the range select to rotate the map like u had in your demo.....
and then taking it from there

**Comment by Raruto** [comment]
Hi cubecleveland,

I honestly don't see any issues here: https://jsfiddle.net/upcozms9/

**Comment by cubecleveland** [comment]
Sorry, maybe im not understaing you correctly or just being a total novice,., but we are trying to control the rotate ourself with a range, (exactly as u have in your demo).... what would be the function call to riatte the map dynamically ?

**Comment by Raruto** [comment]
In that example this is the file that adds the range slider

https://github.com/Raruto/leaflet-rotate/blob/628f2ea586b5b16d801c9ffd71cbc8a0ade9a295/examples/leaflet-rotate.html#L20

https://github.com/Raruto/leaflet-rotate/blob/628f2ea586b5b16d801c9ffd71cbc8a0ade9a295/examples/leaflet-rotate.html#L122

---

In particular you take a look at these lines:

https://github.com/Raruto/leaflet-rotate/blob/628f2ea586b5b16d801c9ffd71cbc8a0ade9a295/lib/debug.js#L107

https://github.com/Raruto/leaflet-rotate/blob/628f2ea586b5b16d801c9ffd71cbc8a0ade9a295/lib/debug.js#L160

https://github.com/Raruto/leaflet-rotate/blob/628f2ea586b5b16d801c9ffd71cbc8a0ade9a295/lib/debug.js#L163-L164

_Have nice day,
Raruto_

**Comment by cubecleveland** [comment]
Hi, first thank so much for all your help trying to make this work for us!!!

The samples and cosesandboxes i created worked fine, problem we are facing now is that we actually use React Leaflet in the background and i dont think i can pass the rotate: true to the library, have u ever implemented this with react or otherwise can i pass rotation to the map const after instansiation ?

**Comment by Raruto** [comment]
> can i pass rotation to the map const after instansiation ?

Maybe, I don't use react, for this kind of thing search on stackoverflow or ask on dedicated support forums.

_Raruto_

**Comment by cubecleveland** [comment]
Thanks, it actually works perfect with react.
In the jfiddle u sent me.... the control that is incharge of the rotation disappears if u click  on it 1 or 2 times.... is this the expected behaviour

**Comment by Raruto** [comment]
> In the jfiddle u sent me.... the control that is incharge of the rotation disappears if u click on it 1 or 2 times.... is this the expected behaviour

You can use this option to prevent the button from disappearing:

```js
rotate: true,
rotateControl: {
  closeOnZeroBearing: false
},
```

if you are also interested in why it changes background color take a look at the following file:

https://github.com/Raruto/leaflet-rotate/blob/master/src/control/Rotate.js

_Raruto_

**Comment by cubecleveland** [comment]
Works, great,

Love this feature but missiung some docs about how to do normal stuff like dynamically change the rotation,  Get current rotation etc... i wishs there was a very quick manual with those calls

**Comment by Raruto** [comment]
it's not a huge library, however:

https://github.com/Raruto/leaflet-rotate/blob/628f2ea586b5b16d801c9ffd71cbc8a0ade9a295/src/map/Map.js#L68-L89

**Comment by cubecleveland** [comment]
Wonderful, my implementation is done ?
The only missing piece for me here is that i rotate the map and then i save the rotation angle... i want to then relaod it when i reolod the map ? I assume i need to listen to the rotate event and then store the breading in Local storage ? is that possible ?

**Comment by Raruto** [comment]
You can pass the `bearing` option when initializing the map:

https://github.com/Raruto/leaflet-rotate/blob/628f2ea586b5b16d801c9ffd71cbc8a0ade9a295/src/map/Map.js#L6-L19

 the rest is up to you

**Comment by cubecleveland** [comment]
That worked out great!
I have 1 morea question andi think e are good! 
CAn we apply the rotation only on the tile layer ?
Leaving all other layers untouched ?

**Comment by Raruto** [comment]
I only did such a thing once, [here](https://github.com/Raruto/leaflet-elevation/blob/3f7f4383248befd5fbec053c2883148435b89664/src/control.js#L615-L628) it is the relative portion of code:

```js
_initMarker: function(map) {
  let pane                   = map.getPane('elevationPane');
  if (!pane) {
    pane = this._pane        = map.createPane('elevationPane', map.getPane('norotatePane') || map.getPane('mapPane'));
    pane.style.zIndex        = 625; // This pane is above markers but below popups.
    pane.style.pointerEvents = 'none';
  }

  if (this._renderer) this._renderer.remove()
  this._renderer             = L.svg({ pane: "elevationPane" }).addTo(this._map); // default leaflet svg renderer
  this._marker               = new Marker(this.options);

  this._fireEvt("elechart_marker");
},
```

In this [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation.html) you can see that by rotating the map the "viewfinder" pane still retains its original rotation.

However, my friend, you should really open a new issue for each different topic...

_Raruto_

**Comment by cubecleveland** [comment]
I will absoutly... Thanks again!
