### ISSUE TITLE
Rotation not applied on GeoJson layer when using a custom pane

### ISSUE THREAD

**Issue by claustres** [Raruto/leaflet-rotate#54]
First of all thanks for this helpful plugin. I've noticed that it does not seem to work when using map panes.

For instance, adding this layer in your demo creates a layer that will not rotate:

```js
const pane = 'geojson';
map.createPane(pane);
const geoJson = L.geoJSON(
  JSON.parse('{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[102,0.5]},"properties":{"prop0":"value0"}},{"type":"Feature","geometry":{"type":"LineString","coordinates":[[102,0],[103,1],[104,0],[105,1]]},"properties":{"prop0":"value0","prop1":0}},{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[100,0],[101,0],[101,1],[100,1],[100,0]]]},"properties":{"prop0":"value0","prop1":{"this":"that"}}}]}'),
  { pane }
).addTo(map);
```

Removing the pane makes it work.

I would be happy to help in fixing it but I might require some insights. If you know how panes are handled in Leaflet maybe you can have an idea why it is broken and help before I dig into the Leaflet source code.

Cheers.

**Comment by claustres** [comment]
I actually found out that you are using panes to make the elements rotate and create a rotate/non rotate pane (for labels). If I uncomment the `createPane()` function in your code then it works fine for my GeoJson layer.

However, in a more complex exemple I have, where we use custom panes and custom label markers, it appears the markers rotate as well, which is undesired. Indeed we are using `createPane(name)` without specifying any container but it seems to me that when using your plugin we should take care to define the right container when creating panes depending on if it should be affected or not by rotation.

Let me know why you initially commented the `createPane()` function as it might have undesired behaviour I am not aware of.

**Comment by Raruto** [comment]
Hi @claustres,

I think it's been asked before: https://github.com/Raruto/leaflet-rotate/issues/2

👋 Raruto

**Comment by claustres** [comment]
Thanks for your reply I missed this one.
