### ISSUE TITLE
Can you offer any advice how to get this working with React-Leaflet.

### ISSUE THREAD

**Issue by laurencefass** [Raruto/leaflet-rotate#9]
Ive installed the module via npm and im not sure how to use it with React-leaflet.

I have installed the module with yarn and I was kind of hoping that would do all the necessary modifications to the leaflet object automatically.

Ive [created a sandbox](https://codesandbox.io/s/react-leaflet-forked-me1he5?file=/src/index.js) which renders your demo code (HTML, Leaflet, no React) in the index.html file alongside a failed attempt at rendering a rotating map in React-Leaflet. 

The problem is your properties and methods aren't exposed on the Leaflet object exposed by React-Leaflet. Im not sure if this is a React, Leaflet, React-leaflet problem or a problem trying to use ES6 imports so grateful for any insightes and advice.

**Comment by Raruto** [comment]
Hi laurence,

I don't use react, so maybe there are smarter ways than the following: [how-to-add-method-to-class-without-creating-new-class-that-extends-it](https://stackoverflow.com/questions/36904971/how-to-add-method-to-class-without-creating-new-class-that-extends-it), which is basically the same method I used to alter almost all the leaflet classes (although leaflet doesn't actually use classes):

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/map/Map.js#L4

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/layer/vector/Canvas.js#L4

https://github.com/Raruto/leaflet-rotate/blob/6bfcccecf50143fd927e5f347a3f4d5a930c2f56/src/layer/tile/GridLayer.js#L4

I haven't checked the names, but to understand yours it might be something like that:

```js
MapContainer.prototype.options.rotate = true
```

where `MapContainer` is the name of the class you want to alter.

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
I close here due to inactivity, for those interested you can find a related topic here in detail: https://github.com/PaulLeCam/react-leaflet/issues/976
